require 'rails_helper'
describe "Business Intelligence", type: :request do
  describe "getting total market revenue within a range" do
    before :each do
      @merchant = Merchant.create(name: "me")
      @merchant_2 = Merchant.create(name: "not me")

      item = Item.create(name: "item sold", description: "item has been sold and will count towards revenue", unit_price: 2431341, merchant: @merchant)
      item_not_sold = Item.create(name: "item not sold", description: "nobody bought it because its so expensive, this won't count towards revenue!", unit_price: 100007807807807807807070, merchant: @merchant)
      not_my_item = Item.create(name: "item sold", description: "this got sold but isn't mine so it wont count towards revenue", unit_price: 12312, merchant: @merchant_2)

      customer = Customer.create(first_name: "John", last_name: "Smith")

      my_invoice = Invoice.create(customer: customer, merchant: @merchant, status: "shipped", created_at: "2-1-2021".to_date.to_datetime)
      InvoiceItem.create(item: item, invoice: my_invoice, quantity: 5, unit_price: 10)
      Transaction.create(invoice: my_invoice, result: "success")

      my_incomplete_invoice = Invoice.create(customer: customer, merchant: @merchant, status: "shipped", created_at: "2-1-2021".to_date.to_datetime)
      InvoiceItem.create(item: item_not_sold, invoice: my_incomplete_invoice, quantity: 1, unit_price: 100007807807807807807070)
      Transaction.create(invoice: my_incomplete_invoice, result: "failed") #not good


      not_my_invoice = Invoice.create(customer: customer, merchant: @merchant_2, status: "shipped", created_at: "1-1-2021".to_date.to_datetime)
      InvoiceItem.create(item: not_my_item, invoice: not_my_invoice, quantity: 5, unit_price: 100)
      Transaction.create(invoice: not_my_invoice, result: "success")
    end

    it "returns 400 when no start or end date is provided" do
      get api_v1_revenue_path
      expect(response.status).to eq(400)
    end

    it "returns total revenue generated by invoices created within start and end date if provided" do
      start_date = '5-1-2021'
      end_date = '5-2-2021'
      get api_v1_revenue_path(start_date: start_date, end_date: end_date)
      expect(response.status).to eq(200)

      json = JSON.parse(response.body, symbolize_names: true)
      expect(json).to eq({
        data: {
          type: "revenue",
          id: nil,
          attributes: {
            revenue: Invoice.total_revenue_within_range(start_date, end_date)
          }
        }
      })
    end

    it "returns 400 if the start date is after the end date" do
      start_date = '5-2-2021'
      end_date = '5-1-2021'
      get api_v1_revenue_path(start_date: start_date, end_date: end_date)
      expect(response.status).to eq(400)
    end
  end
end
