require 'rails_helper'
describe "Business Intelligence", type: :request do
  describe "getting total market revenue within a range" do
    before :each do
      @merchant = Merchant.create(name: "me")
      @merchant_2 = Merchant.create(name: "not me")

      item = Item.create(name: "item sold", description: "item has been sold and will count towards revenue", unit_price: 2431341, merchant: @merchant)
      item_not_sold = Item.create(name: "item not sold", description: "nobody bought it because its so expensive, this won't count towards revenue!", unit_price: 100007807807807807807070, merchant: @merchant)
      not_my_item = Item.create(name: "item sold", description: "this got sold but isn't mine so it wont count towards revenue", unit_price: 12312, merchant: @merchant_2)

      customer = Customer.create(first_name: "John", last_name: "Smith")

      my_invoice = Invoice.create(customer: customer, merchant: @merchant, status: "shipped", created_at: "2-1-2021".to_date.to_datetime)
      InvoiceItem.create(item: item, invoice: my_invoice, quantity: 5, unit_price: 10)
      Transaction.create(invoice: my_invoice, result: "success")

      my_incomplete_invoice = Invoice.create(customer: customer, merchant: @merchant, status: "shipped", created_at: "2-1-2021".to_date.to_datetime)
      InvoiceItem.create(item: item_not_sold, invoice: my_incomplete_invoice, quantity: 1, unit_price: 100007807807807807807070)
      Transaction.create(invoice: my_incomplete_invoice, result: "failed") #not good


      not_my_invoice = Invoice.create(customer: customer, merchant: @merchant_2, status: "shipped", created_at: "1-1-2021".to_date.to_datetime)
      InvoiceItem.create(item: not_my_item, invoice: not_my_invoice, quantity: 5, unit_price: 100)
      Transaction.create(invoice: not_my_invoice, result: "success")
    end

    it "returns the revenue of the entire system when no start or end date is provided" do
      get api_v1_market_total_revenue_within_range_path
      expect(response.status).to eq(200)

      json = JSON.parse(response.body, symbolize_names: true)
      expect(json).to eq({data: Invoice.total_revenue_within_range(nil,nil)})
    end

    it "returns total revenue generated by invoices created within start and end date if provided" do
      get api_v1_market_total_revenue_within_range_path(start_date: '5-1-2021', end_date: '5-2-2021')
      expect(response.status).to eq(200)

      json = JSON.parse(response.body, symbolize_names: true)
      expect(json).to eq({data: Invoice.total_revenue_within_range('5-1-2021', '5-2-2021')})
    end

    it "returns 0 if no revenue was generated in the given time period" do
      get api_v1_market_total_revenue_within_range_path(start_date: '5-2-2021',end_date: '7-2-2021')
      expect(response.status).to eq(200)

      json = JSON.parse(response.body, symbolize_names: true)
      expect(json).to eq({data: Invoice.total_revenue_within_range('5-2-2021', '7-2-2021')})
    end
  end
end
